; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ONBOX APP FOR REVIT 2019-2026 SOFTWARE"
#define MyAppVersion "1.1.6.0" 
#define MyFork "L-BIM-T_PR2A"
#define MyAppPublisher "ONBOX Engenharia (LetsBIMtogether Fork)"
#define MyAppURL "https://github.com/LetsBIMtogether/OnboxApp"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{045DF2BF-62B7-4EA9-A796-18C8E91DD9A6}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
; Install directly
DefaultDirName={commonappdata}\Autodesk\ApplicationPlugins\OnboxApp.bundle
DisableDirPage=yes
DisableProgramGroupPage=yes
DefaultGroupName={#MyAppName}        
; ; Removing for now... Less to manage :D
; LicenseFile = EULA.rtf
; InfoBeforeFile=I:\5 PROJECTS\11 GITHUB\1 ONBOX APP\OnboxApp\Install\BETA VERSION.txt
SetupIconFile=I:\5 PROJECTS\11 GITHUB\1 ONBOX APP\OnboxApp\Install\onbox_install_icon.ico
Compression=lzma
SolidCompression=yes
WizardSmallImageFile =I:\5 PROJECTS\11 GITHUB\1 ONBOX APP\OnboxApp\Install\InstallerCornerLogo.bmp
WizardImageFile =I:\5 PROJECTS\11 GITHUB\1 ONBOX APP\OnboxApp\Install\InstallerMainLogo.bmp
UninstallFilesDir={app}\_uninstall
UninstallDisplayName=Uninstall OnboxApp {#MyAppVersion} {#MyFork}
DisableWelcomePage=no
OutputBaseFilename=OnboxApp_Install_1160-LBIMT-PR2A 

[Languages]        
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"


[Files]
; Copy files to {app} which = DefaultDirName 
Source: "I:\5 PROJECTS\11 GITHUB\1 ONBOX APP\OnboxApp\OnboxApp.bundle\*"; \
    DestDir: "{app}"; \
    Flags: recursesubdirs createallsubdirs

[UninstallDelete]
Type: filesandordirs; Name: "{app}"

